var cheerio = require('cheerio');
var fs = require('fs');
var request = require("request");

var HTML = [];
var htmlLinks = [];
var domainURL = {
  url: 'http://shirts4mike.com/shirts.php'
};

var Scraper = require("./scraper.js");
var querystring = require("querystring");

// Autogenerated, do not edit. All changes will be undone.
request({
  url: 'http://shirts4mike.com/shirts.php',
  method: "GET",
  timeout: 10000,
  followRedirect: true,
  maxRedirects: 10
}, function(error, response, body) {
  this.body = body;
  HTML.push(body);
  console.log(`${HTML}`);

  var $ = cheerio.load(body);
  $(".products li > a").each(function() {
    var link = $(this);
    var text = link.text();
    var href = link.attr("href");

    console.log(text + " -> " + href);
    htmlLinks.push({
      'url': href
    });
  });
  // console.log(domainURL.url);
});
// Scraper();
function home(request, response) {

  if (request.url === "/") {
    console.log('at url /');

    response.writeHead(200, {
      'Content-Type': 'text/html'
    });
    response.write('<p>Header</p>\n');
    response.write("Main\n");
    response.write(`${HTML}`);

    for (var i = 0; i < htmlLinks.length; i++) {
      response.write(`${htmlLinks[i].url}\n`);
    }
    // END response;
    response.end();
  }
}
var shirtData = [];

function shirt(request, response) {

  var shirtUrl = request.url.replace("/", "");

  // for (var i = 0; i < htmlLinks.length; i++) {
  // response.write(`${htmlLinks[i].url}\n`);

  // && shirtUrl === request.url
  if (shirtUrl.length > 0) {
    console.log(`${shirtUrl}`, 'URL');

    response.writeHead(200, {
      'Content-Type': 'text/html'
    });
    response.write("Header\n<br>");
    response.write(`${shirtUrl}\n <br>`);

    // var shirtInfo = new Scraper(shirtUrl);
    // response.write(`${shirtInfo}`);


// loadData();
    // function loadData() {


      for (var i = 0; i < htmlLinks.length; i++) {
        var shirtInfo = new Scraper(htmlLinks[i].url);

        // console.log(htmlLinks.length, [i], i);

        shirtInfo.on("end", function(profileJSON) {
          //Store the values which we need
          var values = {
            name: profileJSON.h1,
            link: profileJSON.link,
            text: profileJSON.text,
            href: profileJSON.href,
            price: profileJSON.price
          };


          //Simple response
          // renderer.view("profile", values, response);
          // renderer.view("footer", {}, response);
          response.write(values.href + " URL Value " + '<br>' + values.name + "<br> For the Price of " + values.price + '<br>');
          response.write(values.price + '<br>' + values.text + `<p> All Data </p> <br>`);
          // response.end('Footer\n');
          shirtData.push(values);


        });
        if (i === htmlLinks.length - 1) {
          saveData(shirtData);
          
        } else {
          console.log('Loading data......');
        }
      } // End of Four loop;

    // response.end('Footer\n');

    // Create correct formate for .csv files.
    function dataFormate(data) {

    }

    function saveData (data) {
      this.data = data;
      var dataToWrite = JSON.stringify(data);
      var fs = require('fs');

      fs.writeFile('Shirt_Data.csv', dataToWrite, 'utf8', function (err) {
      if (err) {
        console.log('Some error occured - file either not saved or corrupted file saved.');
      } else{
        console.log('It\'s saved!');
      }
      });
    }
  }
  // else
  // {
  // response.write("Not Found\n");

  // }
  // }



  // response.end();
}




module.exports.home = home;
module.exports.shirt = shirt;
