// use 'esversion: 6';

var cheerio = require('cheerio');
var fs = require('fs');
var request = require("request");

function shirt(req, response) {
     // Scraper call config.
    var config = {
      url: 'http://shirts4mike.com/shirts.php/',
      method: "GET",
      timeout: 10000,
      followRedirect: true,
      maxRedirects: 10,
      url2: 'http://shirts4mike.com/'
    };
      // Autogenerated, do not edit. All changes will be undone.
      request(
        config,
        function(error, response, body) {
          var shirts = [];

        if (!error && response.statusCode === 200) {
          var $ = cheerio.load(body);

          var href = $('ul.products li a');
          href.each(function() {
              var shirtUrl = config.url2 + $(this).attr('href');

              request(shirtUrl, function (error, response, body) {

                if (!error && response.statusCode === 200) {
                  var $ = cheerio.load(body);
                  var shirt = {};

                  shirt.price = $('.price').text();
                  shirt.title = $('title').text();
                  shirt.href = shirtUrl;
                  shirt.imageUrl = config.url2 + $('.shirt-picture img').attr('src');

                  shirts.push(shirt);
                }

                if (href.length === shirts.length) {
                  // // NOTE: Sort by shirt link number values starting at one.
                  function compare(a, b) {
                    if (a.href < b.href)
                      return -1;
                    if (a.href > b.href)
                      return 1;
                      return 0;
                    }
                    saveData(shirts.sort(compare));
                  } else {
                    console.log('Loading data...... ', shirts.length, ' of ', href.length, 'files loaded.');
                  }
            }); // End of request call;
          });
        }
      });
      // // NOTE: Save data to .csv file.
          function saveData (data) {
            this.data = data;
            var fs = require('fs');

              var dataToWrite = '';
              var newRow = ',,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,';

                for (var i = 0; i < data.length; i++) {
                   dataToWrite +=
                      data[i].title  + ',' +
                      data[i].price + ',' +
                      data[i].href  + ',' +
                      data[i].imageUrl +
                      newRow + '\n';
                }
                // Check if data holds real data.
                if (dataToWrite) {
                  // Write and save file.
                  var today = new Date();
                  var dd = today.getDate();
                  var mm = today.getMonth()+1; //January is 0!
                  var yyyy = today.getFullYear();
                  var fileDateCreated = `${yyyy}-${mm}-${dd}.csv`;

                  // Write data to a .csv file formate with the date it was created.
                  fs.writeFile(`./data/${fileDateCreated}`, dataToWrite, 'utf8', function (err) {
                    if (err) {
                      console.log('Some error occured - file either not saved or corrupted file saved.');
                      console.log(err);
                    } else {
                      console.log(`File saved successfully! You can view the data file saved at ./data/${fileDateCreated}`);
                      response.end();
                    }
                  });
                }
          }
  if (req.url === "/") {
      response.writeHead(200, {
        'Content-Type': 'text/html'
      });
      response.write("Header\n<br>");
      response.end();
    }
}

module.exports.shirt = shirt;
